Repository vshn/provider-exoscale, pull requests merged in 2022-11, with the labels that each got.

#55 fix postgres e2e tests
  test/e2e/postgresql/01-connect.yaml
Labels: bug

#53 Release crossplane package to upbound market
  .github/workflows/release.yml
  Makefile.vars.mk
  package/crossplane.yaml.template
  package/package.mk
  test/local.mk
Labels: enhancement

#58 Upper-case Redis connection details
  operator/rediscontroller/controller_test.go
  operator/rediscontroller/observe.go
Labels: change

#57 refactoring postgresql controller
  apis/exoscale/v1/dbaas_types.go
  apis/exoscale/v1/dbaas_types_test.go
  operator/mapper/alias.go
  operator/mapper/alias_test.go
  operator/mapper/dbaas_test.go
  operator/mapper/error.go
  operator/mapper/postgresql.go
  operator/mapper/postgresql_test.go
  operator/mapper/redis.go
  operator/postgresqlcontroller/connector.go
  operator/postgresqlcontroller/create.go
  operator/postgresqlcontroller/delete.go
  operator/postgresqlcontroller/observe.go
  operator/postgresqlcontroller/observe_test.go
  operator/postgresqlcontroller/pipeline.go
  operator/postgresqlcontroller/setup.go
  operator/postgresqlcontroller/update.go
Labels: change

#61 Fix panic in node state mapping
  operator/mapper/alias.go
  operator/mapper/alias_test.go
Labels: bug
