Repository vshn/provider-exoscale, pull requests merged in 2022-12, with the labels that each got.

#62 Add Support for Kafka
  apis/exoscale/v1/kafka_types.go
  apis/exoscale/v1/zz_generated.deepcopy.go
  apis/exoscale/v1/zz_generated.managed.go
  apis/exoscale/v1/zz_generated.managedlist.go
  docs/modules/ROOT/examples/exoscale_iamkey.yaml
  generate_sample.go
  go.mod
  operator/kafkacontroller/controller.go
  operator/kafkacontroller/create.go
  operator/kafkacontroller/create_test.go
  operator/kafkacontroller/delete.go
  operator/kafkacontroller/delete_test.go
  operator/kafkacontroller/observe.go
  operator/kafkacontroller/observe_test.go
  operator/kafkacontroller/update.go
  operator/kafkacontroller/update_test.go
  operator/kafkacontroller/webhook.go
  operator/kafkacontroller/webhook_test.go
  operator/operator.go
  package/crds/exoscale.crossplane.io_kafkas.yaml
  package/webhook/manifests.yaml
  samples/exoscale.crossplane.io_kafka.yaml
  test/e2e/kafka/00-assert.yaml
  test/e2e/kafka/00-install.yaml
  test/e2e/kafka/01-assert.yaml
  test/e2e/kafka/01-connect.yaml
  test/e2e/kafka/02-delete.yaml
Labels: enhancement

#68 Add Kafka REST support
  apis/exoscale/v1/kafka_types.go
  apis/exoscale/v1/zz_generated.deepcopy.go
  operator/kafkacontroller/create.go
  operator/kafkacontroller/observe.go
  operator/kafkacontroller/observe_test.go
  operator/kafkacontroller/update.go
  package/crds/exoscale.crossplane.io_kafkas.yaml
  samples/exoscale.crossplane.io_kafka.yaml
  test/e2e/kafka/00-install.yaml
  test/e2e/kafka/02-assert.yaml
  test/e2e/kafka/02-connect-rest.yaml
  test/e2e/kafka/03-delete.yaml
Labels: enhancement

#69 remove ca.crt from redis conn details
  operator/rediscontroller/controller_test.go
  operator/rediscontroller/observe.go
  test/e2e/redis/01-connect.yaml
Labels: change

#70 Increase timeouts for Kafka e2e tests
  test/e2e/kafka/00-assert.yaml
  test/e2e/kafka/01-assert.yaml
  test/e2e/kafka/02-assert.yaml
Labels: bug

#72 Add missing resources to e2e-test-clean
  test/local.mk
Labels: enhancement

#74 on behalf of component-appcat refactor, I switched version variable n…
  apis/exoscale/v1/opensearch_types.go
  generate_sample.go
  operator/opensearchcontroller/create.go
  operator/opensearchcontroller/observe.go
  operator/opensearchcontroller/webhook.go
  package/crds/exoscale.crossplane.io_opensearches.yaml
  samples/exoscale.crossplane.io_opensearch.yaml
Labels: change

#73 improve version validation on DBaaS
  generate_sample.go
  operator/kafkacontroller/observe_test.go
  operator/kafkacontroller/webhook.go
  operator/kafkacontroller/webhook_test.go
  operator/mysqlcontroller/setup.go
  operator/mysqlcontroller/webhook.go
  operator/opensearchcontroller/setup.go
  operator/opensearchcontroller/webhook.go
  operator/postgresqlcontroller/setup.go
  operator/postgresqlcontroller/webhook.go
  operator/rediscontroller/webhook.go
  operator/webhook/validate.go
  operator/webhook/validate_test.go
  samples/exoscale.crossplane.io_kafka.yaml
  test/e2e/kafka/00-assert.yaml
  test/e2e/kafka/00-install.yaml
Labels: enhancement

#76 Add 2 new fields in connection secret
  operator/opensearchcontroller/observe.go
Labels: enhancement
